[build]
target = "index.html"
dist = "dist"
public_url = "/rar-to-zip/"

[watch]
ignore = ["target"]

[serve]
port = 8080
open = false

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "npm run build:css"]
